[platformio]
default_envs = esp32_2432s028

[env:esp32_2432s028r]
platform = espressif32@6.8.1
board = esp32dev
framework = arduino

board_build.partitions = partitions.csv
board_build.filesystem = littlefs

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 460800

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -I include
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -D CORE_DEBUG_LEVEL=3
    -D KEEZER_BOARD_CYD_ST7789_2USB=1
    -D KEEZER_ENABLE_COMPRESSOR_GPIO=1
    -D KEEZER_PHASE1_SD_SMOKE_TEST=1
    -D KEEZER_DEMO_MODE=0
    -D KEEZER_DEMO_AUTOPLAY=0
    -D KEEZER_SCALE_USE_HTTP=1

lib_deps =
    lvgl/lvgl@9.5.0
    lovyan03/LovyanGFX@1.2.25

[env:esp32_2432s028]
extends = env:esp32_2432s028r
