#pragma once

#include <Arduino.h>

namespace balanca::web {

inline constexpr char kIndexHtml[] PROGMEM = R"HTML(<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Balança · Control de Barril</title><style>
:root{color-scheme:dark;--bg:#08110e;--card:#111e19;--line:#263b32;--green:#72e39a;--muted:#9bb0a5;--bad:#ff7a7a;--warn:#ffd166}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% -20%,#1a3d2c 0,var(--bg) 46%);color:#f4fbf6;font:16px system-ui,-apple-system,Segoe UI,sans-serif}
main{width:min(760px,100%);margin:auto;padding:22px 16px 42px}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.brand{font-weight:800;letter-spacing:.06em}.pill{border:1px solid var(--line);border-radius:999px;padding:7px 11px;color:var(--muted);font-size:13px}.online{color:var(--green);border-color:#397954}.offline{color:var(--bad);border-color:#7e3f3f}
.hero,.card{background:linear-gradient(145deg,#15251e,#0d1814);border:1px solid var(--line);box-shadow:0 16px 38px #0006;border-radius:18px}.hero{text-align:center;padding:28px 16px;margin-bottom:14px}.eyebrow{font-size:12px;letter-spacing:.15em;color:var(--muted)}#weight{font-size:clamp(52px,14vw,92px);font-weight:850;letter-spacing:-.06em;line-height:1.05;margin:8px 0}.unit{font-size:.35em;color:var(--muted);letter-spacing:0}.stable{color:var(--green)}.moving{color:var(--warn)}
.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.card{padding:18px}.card h2{font-size:15px;margin:0 0 14px;color:var(--green)}.metric{font-size:24px;font-weight:750}.muted{color:var(--muted)}dl{display:grid;grid-template-columns:1fr auto;gap:10px;margin:0}dt{color:var(--muted)}dd{margin:0;text-align:right}.wide{grid-column:1/-1}
button,input{font:inherit;border-radius:10px;padding:11px 13px}button{border:0;background:var(--green);color:#06100b;font-weight:800;cursor:pointer}button.secondary{background:#263b32;color:#eaf7ee}button.danger{background:#6e2929;color:#fff}button:disabled{opacity:.5}input{width:100%;border:1px solid var(--line);background:#09130f;color:#fff;margin:6px 0 10px}.actions{display:flex;flex-wrap:wrap;gap:9px}.message{min-height:24px;margin-top:10px;color:var(--muted)}details{margin-top:14px}summary{cursor:pointer;color:var(--green);font-weight:700}.networks{display:grid;gap:6px;margin:8px 0}.networks button{text-align:left;background:#1d3028;color:#fff}.danger-zone{border-color:#603434}
@media(max-width:580px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}main{padding-top:14px}.hero{padding:24px 12px}}
</style></head><body><main>
<header><div><div class="brand">CONTROL DE BARRIL</div><div class="muted">Balança autônoma</div></div><span id="connection" class="pill offline">CONECTANDO</span></header>
<section class="hero"><div class="eyebrow">PESO ATUAL</div><div id="weight">--.-- <span class="unit">kg</span></div><div id="stability" class="moving">AGUARDANDO LEITURA</div></section>
<div class="grid">
<section class="card"><h2>IDENTIFICAÇÃO NFC</h2><div id="nfc" class="metric">SEM CARTÃO</div><div id="nfcState" class="muted">PN532 aguardando</div></section>
<section class="card"><h2>DIAGNÓSTICO</h2><dl><dt>HX711</dt><dd id="hx">--</dd><dt>PN532</dt><dd id="pn">--</dd><dt>OLED</dt><dd id="oled">--</dd><dt>Memória livre</dt><dd id="heap">--</dd></dl></section>
<section class="card wide"><h2>CALIBRAÇÃO</h2><p class="muted">Faça a tara com a plataforma vazia. Depois coloque uma massa conhecida, espere ficar estável e informe o valor.</p><div class="actions"><button id="tare">Fazer tara</button></div><label for="reference">Massa conhecida (kg)</label><input id="reference" type="number" min="0.001" step="0.001" placeholder="Ex.: 10.000"><button id="calibrate" class="secondary">Calibrar com peso conhecido</button><div id="calMessage" class="message"></div></section>
<section class="card wide"><h2>REDE</h2><dl><dt>Wi-Fi</dt><dd id="ssid">--</dd><dt>Endereço</dt><dd id="ip">--</dd><dt>Sinal</dt><dd id="rssi">--</dd><dt>API</dt><dd><a href="/api/v1/reading" style="color:var(--green)">/api/v1/reading</a></dd></dl><details><summary>Alterar rede Wi-Fi</summary><button id="scan" class="secondary" style="margin-top:12px">Buscar redes</button><div id="networks" class="networks"></div><input id="wifiSsid" maxlength="32" placeholder="Nome da rede"><input id="wifiPassword" maxlength="64" type="password" placeholder="Senha"><button id="saveWifi">Salvar e conectar</button><div id="wifiMessage" class="message"></div></details></section>
<section class="card wide danger-zone"><h2>SISTEMA</h2><dl><dt>Firmware</dt><dd>HTTP v1 + OTA</dd><dt>Tempo ligado</dt><dd id="uptime">--</dd><dt>Fator HX711</dt><dd id="factor">--</dd></dl><div class="actions" style="margin-top:14px"><button onclick="location.href='/update'">Atualizar firmware</button><button id="restart" class="secondary">Reiniciar</button><button id="reset" class="danger">Restaurar fábrica</button></div><div id="systemMessage" class="message"></div></section>
</div></main><script>
const $=id=>document.getElementById(id);const post=async(url,data={})=>{const body=new URLSearchParams(data);const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const j=await r.json().catch(()=>({ok:false,message:'Resposta inválida'}));if(!r.ok)throw new Error(j.message||j.error||'Falha');return j};
const health=(id,ok)=>{$(id).textContent=ok?'OK':'ERRO';$(id).style.color=ok?'var(--green)':'var(--bad)'};
async function refresh(){try{const s=await fetch('/api/v1/status',{cache:'no-store'}).then(r=>r.json());$('connection').textContent=s.provisioning?'MODO CONFIG.':(s.wifi_connected?'ONLINE':'SEM WI-FI');$('connection').className='pill '+((s.wifi_connected||s.provisioning)?'online':'offline');$('weight').innerHTML=s.weight_valid?(s.weight_grams/1000).toFixed(2)+' <span class="unit">kg</span>':'--.-- <span class="unit">kg</span>';$('stability').textContent=s.weight_valid?(s.stable?'ESTÁVEL':'EM MOVIMENTO'):'LEITURA INDISPONÍVEL';$('stability').className=s.stable?'stable':'moving';$('nfc').textContent=s.nfc_uid||'SEM CARTÃO';$('nfcState').textContent=s.pn532_ok?(s.nfc_uid?'Cartão detectado':'Aproxime um cartão'):'PN532 indisponível';health('hx',s.hx711_ok);health('pn',s.pn532_ok);health('oled',s.oled_ok);$('heap').textContent=Math.round(s.free_heap/1024)+' KB';$('ssid').textContent=s.wifi_ssid||'Não conectado';$('wifiSsid').value=$('wifiSsid').value||s.wifi_ssid||'';$('ip').textContent=s.ip;$('rssi').textContent=s.wifi_connected?s.rssi_dbm+' dBm':'--';$('uptime').textContent=Math.floor(s.uptime_ms/1000)+' s';$('factor').textContent=s.calibration_factor.toFixed(2)}catch(e){$('connection').textContent='DESCONECTADA';$('connection').className='pill offline'}}
async function action(button,url,data,target){button.disabled=true;try{const r=await post(url,data);$(target).textContent=r.message}catch(e){$(target).textContent=e.message}finally{button.disabled=false;refresh()}}
$('tare').onclick=()=>action($('tare'),'/api/v1/actions/tare',{},'calMessage');$('calibrate').onclick=()=>{const kg=parseFloat($('reference').value);if(!kg||kg<=0){$('calMessage').textContent='Informe uma massa válida.';return}action($('calibrate'),'/api/v1/actions/calibrate',{reference_grams:Math.round(kg*1000)},'calMessage')};
$('scan').onclick=async()=>{const box=$('networks');box.textContent='Buscando...';try{const list=await fetch('/api/v1/wifi/scan').then(r=>r.json());box.innerHTML='';list.networks.forEach(n=>{const b=document.createElement('button');b.type='button';b.textContent=n.ssid+' ('+n.rssi_dbm+' dBm)';b.onclick=()=>{$('wifiSsid').value=n.ssid};box.appendChild(b)});if(!list.networks.length)box.textContent='Nenhuma rede encontrada.'}catch(e){box.textContent='Falha ao buscar redes.'}};
$('saveWifi').onclick=()=>action($('saveWifi'),'/api/v1/config/wifi',{ssid:$('wifiSsid').value,password:$('wifiPassword').value},'wifiMessage');$('restart').onclick=()=>action($('restart'),'/api/v1/actions/restart',{},'systemMessage');$('reset').onclick=()=>{if(confirm('Apagar Wi-Fi, tara e calibração?'))action($('reset'),'/api/v1/actions/factory-reset',{},'systemMessage')};refresh();setInterval(refresh,500);
</script></body></html>)HTML";

inline constexpr char kOtaHtml[] PROGMEM = R"HTML(<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Atualizar balanca</title><style>
body{margin:0;background:#08110e;color:#f4fbf6;font:16px system-ui,sans-serif}main{max-width:520px;margin:8vh auto;padding:20px}.card{background:#111e19;border:1px solid #263b32;border-radius:18px;padding:24px}h1{font-size:22px;color:#72e39a}input,button{width:100%;box-sizing:border-box;padding:13px;margin-top:12px;border-radius:10px;font:inherit}input{background:#09130f;color:#fff;border:1px solid #395548}button{border:0;background:#72e39a;color:#06100b;font-weight:800}.muted{color:#9bb0a5}.bar{height:10px;background:#263b32;border-radius:8px;overflow:hidden;margin-top:16px}.fill{height:100%;width:0;background:#72e39a}a{color:#72e39a}
</style></head><body><main><div class="card"><h1>ATUALIZAR BALANCA</h1><p class="muted">Selecione somente o firmware <b>.bin</b> da balanca. A rede, tara e calibracao serao preservadas.</p><form id="form"><input id="file" type="file" accept=".bin" required><button>ENVIAR E ATUALIZAR</button></form><div class="bar"><div id="fill" class="fill"></div></div><p id="status" class="muted">Aguardando arquivo.</p><a href="/">Voltar</a></div></main><script>
const form=document.getElementById('form'),file=document.getElementById('file'),fill=document.getElementById('fill'),status=document.getElementById('status');form.onsubmit=e=>{e.preventDefault();if(!file.files.length)return;const data=new FormData();data.append('firmware',file.files[0]);const xhr=new XMLHttpRequest();xhr.open('POST','/update');xhr.upload.onprogress=e=>{if(e.lengthComputable){const p=Math.round(e.loaded*100/e.total);fill.style.width=p+'%';status.textContent='Enviando: '+p+'%'}};xhr.onload=()=>{status.textContent=xhr.responseText};xhr.onerror=()=>{status.textContent='Falha de comunicacao. A balanca nao sera reiniciada.'};xhr.send(data)};
</script></body></html>)HTML";

}  // namespace balanca::web
